# Generated by Django 6.0.1 on 2026-04-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_upi_id',
            field=models.CharField(blank=True, help_text='Seller UPI ID for receiving payouts', max_length=100),
        ),
    ]
